### ISSUE TITLE
Confusing behavior of context collapsing when changing sort order (Linux)

### ISSUE THREAD

**Issue by blue42u** [HPCToolkit/hpcviewer.e4#12]
The un/collapsed status of contexts is not preserved naturally after changing the sorting in the bottom-up and flat views.

Seen on Linux with OpenJDK (13).

To reproduce:
1. Open a database (`hpcrun -e REALTIME@100 ls` suffices, or use [bug-confusing-collapse.zip](https://github.com/HPCToolkit/hpcviewer.e4/files/5086693/bug-confusing-collapse.zip)), switch to bottom-up and open a few contexts:
![image](https://user-images.githubusercontent.com/17242663/90442750-be47ff00-e0a0-11ea-9e03-b3c362fcb27a.png)
2. Change the sorting to another column, note that the previously open contexts are closed, and entirely unrelated contexts are now open:
![image](https://user-images.githubusercontent.com/17242663/90443273-9ad18400-e0a1-11ea-92ab-e985dd4be9e7.png)
3. Repeatedly click column headers, note the open contexts slow propagation down the view:
![image](https://user-images.githubusercontent.com/17242663/90443022-2d255800-e0a1-11ea-95ef-c28b37546c46.png)
4. Continue to click column headers, note that eventually all contexts are closed.
5. Repeat the 2-4 in the flat view, note a similar effect.

**Comment by laksono** [comment]
Yes, every time we sort, Eclipse SWT somehow collapse the tree.
This happens since we use a lazy virtual tree to speed up the rendering. The side-effect of using this policy is Eclipse collapse the tree when we sort a column.
I am experimenting to use another table widget called NatTable (NAT=Not Another Table). This one is much more configurable (we have more control) but really complex.

**Comment by blue42u** [comment]
This appears to no longer be an issue in `develop` (with the NAT table implementation).
